SET GLOBAL event_scheduler=1;
USE PROGETTO_DB;
CREATE EVENT calcolaPromo
ON SCHEDULE EVERY '1' MONTH
STARTS '2022-06-30 23:59:00'
DO
	select 'ciao';
	DROP TABLE IF EXISTS A;
	CREATE TABLE A SELECT * 
	FROM WorstSellers
	ORDER BY CodLibro ASC
	LIMIT 10;
	DROP TABLE IF EXISTS B;
	CREATE TABLE B SELECT * 
	FROM WorstSellers
	ORDER BY CodLibro ASC
	LIMIT 10 OFFSET 10;
	DROP TABLE IF EXISTS C;
	CREATE TABLE C SELECT * 
	FROM WorstSellers
	ORDER BY CodLibro ASC
	LIMIT 10 OFFSET 20;
	CALL applicaProm();
